(6-2)中級 従業員曖昧検索
ke-suke0215/ex-emp-management-bugfix pull request #15
Opened 2022-06-10 05:52 UTC by ke-suke0215

# 実装したこと
従業員の名前曖昧検索
# 実装方法
## リポジトリクラス
名前で曖昧検索を行うfindByNameメソッドを作成
## サービスクラス
曖昧検索を行うリポジトリのメソッドを実行して従業員リストを返すメソッドを作成
## コントローラクラス
### 検索する名前の引数がnull（他の画面から遷移してきた時）
全件検索
### 検索結果が長さが1以上のリストの時
名前曖昧検索の結果を表示
### 検索結果が長さ0のリストの時
全件検索 ＋ 「１件もありませんでした」というメッセージを表示

レビューよろしくお願いします。

2022-06-10 08:02 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-06-10 08:02 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/controller/EmployeeController.java
> +		if(name == null) {
空文字で検索された場合はnullではなく" "で来る認識です。
テストをお願いします。
問題なければ無視で大丈夫です。

2022-06-10 08:02 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/controller/EmployeeController.java
> +		List<Employee> employeeList = new ArrayList<>();
new ArrayList<>();は無駄なインスタンス化です。
employeeListは間も無く57行目や59行目で上書きされるためnullで初期化すればOKです。

2022-06-10 08:16 UTC, ke-suke0215 commented
最新のdevelopをマージしました。

ArrayListのインスタンス化をnullに変更しました。
空文字で検索された際の条件を変更しました。

最新のpushで変更したファイルはEmployeeControllerのみです。

よろしくお願いします。

2022-06-12 23:41 UTC, igamasayuki approved these changes
とてもわかりやすくなったと思います。
承認します。

2022-06-12 23:41 UTC, merged